name: Build and push container image
on:
  push:
    tags: ['[0-9]+.[0-9]+.[0-9]+*']

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Build and publish package
        shell: bash
        run: |
          make package VERSION=${{ github.ref_name }}
          ls -lah
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "*.rpm,SHA256SUMS"
          omitBody: true
